// WebSample/JSViewer_Vue_Core/ClientApp/src/app/components/Viewer.vue
<template>
    <div class="main-container" id="viewerContainer">
    </div>
</template>
<script>

    import {createViewer} from '@mescius/activereportsnet-viewer-ja';
    import "@mescius/activereportsnet-viewer-ja/esm/jsViewer.min.css";
    export default {
        props: ['reportName'],
        mounted() {
            this.viewer = createViewer({
                element: '#viewerContainer'
            });
        },
        watch: {
            reportName() {
                this.viewer.openReport(this.reportName);
            }
        },
    }
</script>
<style>
    .main-container {
      height: 100vh;
      flex: 3;
    }
</style>

// WebSample/JSViewer_React_Core/ClientApp/src/app/components/viewer.js
import React, {Component} from "react";
import {createViewer} from '@mescius/activereportsnet-viewer-ja';

import "@mescius/activereportsnet-viewer-ja/dist/jsViewer.min.css";

export default class Viewer extends Component {
    constructor(props) {
        super(props);
    }

    componentDidMount() {
        this.viewer = createViewer({
            element: '#viewerContainer'
        });
    }

    componentDidUpdate() {
        this.viewer.openReport(this.props.reportName);
    }

    render() {
        return (
            <div className="main-container" id="viewerContainer"/>
        );
    }
}
